### ISSUE TITLE
https://erlang.org returns nothing (only www.* works) 

### ISSUE THREAD

**Issue by mpenet** [erlang/erlang-org#1]
The nginx conf should either redirect root to www or handle requests without vhost (nicer imho).

**Comment by RaimoNiskanen** [comment]
Note that this repo holds the code for www.erlang.org, while erlang.org is a different server.  This erlang.org server will be replaced any time (as I have tried to find the time for, for quite a while), and then it we'll configure it for https as well (probably also change to nginx)...

But this issue is practically unrelated to the www.erlang.org server, and certainly to the code in this repo.
