### ISSUE TITLE
add redirect from erlang.org to www.erlang.org

### ISSUE THREAD

**Issue by derek-zhou** [erlang/erlang-org#53]
There are many existing links to erlang.org/doc from elsewhere, such as Elixir's doc site:

https://hexdocs.pm/elixir/Process.html#flag/2

the links look like:

https://erlang.org/doc/man/erlang.html#demonitor-2

They all timeout now. Maybe we should 301 redirect them to the correct link as:

https://www.erlang.org/doc/man/erlang.html#demonitor-2

**Comment by garazdawi** [comment]
Hello!

There is such a redirect in place, but [because of the downtime](https://erlangforums.com/t/erlang-mailing-lists-and-parts-of-erlang-org-will-be-unavailable-from-friday-14-00-monday-17-00-cet/532) the server that does those redirects is down. So either make a patch to hexdocs to point to www.erlang.org or wait for the server to come back online.

**Comment by eksperimental** [comment]
I have been wanting to report this for a long time.
I think we should unify the docs in one server, and redirect from the one that we don't want. 

> There is such a redirect in place, but [because of the downtime](https://erlangforums.com/t/erlang-mailing-lists-and-parts-of-erlang-org-will-be-unavailable-from-friday-14-00-monday-17-00-cet/532) the server that does those redirects is down. So either make a patch to hexdocs to point to [www.erlang.org](http://www.erlang.org) or wait for the server to come back online.

Was this fixed within the last year? Because last time i checked they were loaded individually in each server, causing people to reload pages twice and not make use of cache, if they were visiting www.erlang.org and erlang.org

Been wanting to report this for a while, suggesting to unify the domains.

**Comment by garazdawi** [comment]
With the release of the new erlang.org we moved the hosting of the docs from erlang.org to www.erlang.org. So about two weeks ago www.erlang.org/doc redirected to Erlang.org/doc, but after the switch we changed it to be the reverse. We have a goal to move so that erlang.org and www.erlang.org are the same server, but that is not done yet which is why this issue popped up.

It is not often that the erlang.org server needs to be down, but as it is hosted on our premises it happens from time to time.
